config/routes.rb
Rails.application.routes.draw do

  resources :pages

  root 'pages#index'
  resources :varsity_members
  resources :tryout_intents
  resources :training_activities
  resources :debt_settlements
  resources :competitions
  resources :contingents
  resources :acquired_quota_points

  devise_for :officer_in_charges

devise_scope :officer_in_charges do
    get "signup", to: "devise/registrations#new"
    get "/signin" => "devise/sessions#new"
    post "/signin" => "devise/sessions#create"
    delete "/logout" => "devise/sessions#destroy"
end

end

app/models/competition_debt.rb
class CompetitionDebt < ActiveRecord::Base
	belongs_to :competition
	belongs_to :varsity_member

	validates :debt_amount, length: { maximum: 3 }, numericality: true
	validates :source_of_debt, presence: true

	validate :cannot_be_negative

	def cannot_be_negative
	 	if self.debt_amount <= 0
	      errors.add(:debt_amount, "Quantity must not be negative or zero!")
	    end
	end

	after_create :update_varisty_member_competition_debt

	def update_varisty_member_competition_debt

    	sum = 0
    	#vm.total_acquired_quota_points*

    	vm = VarsityMember.find(self.varsity_member_id)
    	if vm.total_debt != 0
       		um = vm.total_debt + self.debt_amount 
       		user.update(:total_debt => sum)

    	end
	end

	before_create :check_total_debt

	def check_total_debt
    	vm = VarsityMember.find(self.varsity_member_id)
    	if vm.total_debt == 0
    		raise "ERROR: Varsity Total Debt is already 0" 
    	end
	end
end

app/controllers/competition_debts_controller.rb
class CompetitionDebtsController < ApplicationController
   load_and_authorize_resource
  def index
    @competition_debts = CompetitionDebt.all 

    render(:template => "competition_debts/index")
  end

  def show
    @competition_debt = CompetitionDebt.find(params[:id])
  end

  def new
    @competition_debt = CompetitionDebt.new

    render(:template => "competition_debts/new")
  end

  def create
    @competition_debt = CompetitionDebt.new(competition_debt_params)

    if @competition_debt.save
      redirect_to competition_debt_path(@competition_debt.id)
    else
      render(:template => "competition_debts/index")
    end
  end

  def edit
    @competition_debt = CompetitionDebt.find(params[:id])

    render(:templace => "competition_debts/edit")
  end

  def update
    @competition_debt = CompetitionDebt.find(params[:id])

    if @competition_debt.update(competition_debt_params)
      redirect_to competition_debt_path(@competition_debt)
    else
      render(:template => "competition_debts/edit")
    end
  end

  def destroy
    @competition_debt = CompetitionDebt.find(params[:id])
    @competition_debt.destroy!
    redirect_to competition_debts_path
  end

  def competition_debt_params
    params.require(:competition_debt).permit!
  end
end

app/helpers/competition_debts_helper.rb
module CompetitionDebtsHelper
end

app/views/competition_debts/_form.html.erb
<%= simple_form_for(@competition_debt) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :source_of_debt %>
  </div>

  <div class="form-inputs">
    <%= f.input :debt_amount %>
  </div>

  <div class="form-inputs">
    <%= f.collection_select :competition_id, Competition.all, :id, :name %>
  </div>

  <div class="form-inputs">
    <%= f.association :varsity_member %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/competition_debts/create.html.erb
<h1>CompetitionDebts#create</h1>
<p>Find me in app/views/competition_debts/create.html.erb</p>

app/views/competition_debts/destroy.html.erb
<h1>CompetitionDebts#destroy</h1>
<p>Find me in app/views/competition_debts/destroy.html.erb</p>

app/views/competition_debts/edit.html.erb
<h1>Editing Competition Debt</h1>

<%= render 'form' %>

<%= link_to 'Show', @competition_debt %> |
<%= link_to 'Back', competition_debts_path %>

app/views/competition_debts/index.html.erb
<h1>Listing Competition Debts</h1>

<table>
  <thead>
    <tr>
      <th>Varsity Member</th>
      <th>Competition</th>
      <th>Debt Amount</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @competition_debts.each do |competition_debt| %>
      <tr>
        <td><%= competition_debt.varsity_member %></td>
        <td><%= competition_debt.competition %></td>
        <td><%= number_to_currency(competition_debt.debt_amount, :unit => "Php") %></td>
        <td><%= link_to 'Show', competition_debt %></td>
        <td><%= link_to 'Edit', edit_varsity_member_path(competition_debt) %></td>
        <td><%= link_to 'Destroy', competition_debt, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Competition Debt', new_competition_debt_path %>

app/views/competition_debts/new.html.erb
<h1>New Competition Debt</h1>

<%= render 'form' %>

<%= link_to 'Back', competition_debts_path %>

app/views/competition_debts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Varsity Member:</strong>
  <%= @competition_debt.varsity_member %>
</p>

<p>
  <strong>Competition:</strong>
  <%= @competition_debt.competition %>
</p>

<p>
  <strong>Debt Amount:</strong>
  <%= number_to_currency(@competition_debt.debt_amount, :unit => "Php") %>
</p>

<%= link_to 'Edit', edit_competition_debt_path(@competition_debt) %> |
<%= link_to 'Back', competition_debts_path %>

app/views/competition_debts/update.html.erb
<h1>CompetitionDebts#update</h1>
<p>Find me in app/views/competition_debts/update.html.erb</p>