config/routes.rb
Rails.application.routes.draw do

  resources :pages

  root 'pages#index'
  resources :varsity_members
  resources :tryout_intents
  resources :training_activities
  resources :debt_settlements
  resources :competitions
  resources :contingents
  resources :acquired_quota_points

  devise_for :officer_in_charges

devise_scope :officer_in_charges do
    get "signup", to: "devise/registrations#new"
    get "/signin" => "devise/sessions#new"
    post "/signin" => "devise/sessions#create"
    delete "/logout" => "devise/sessions#destroy"
end

end

app/models/varsity_member.rb
class VarsityMember < ActiveRecord::Base
		TRACK = ["Debater", "Adjudicator", "Debater and Adjudicator"]
	POSITION = ["Contingent Debater", "Contingent Adjudicator", "Non-contingent"]

	validates :vm_id, presence: true, length: { is: 6 }, :uniqueness => { :message => "ID number already exist" }, numericality: true
	validates :first_name, presence: true, length: { maximum: 30}
	validates :last_name, presence: true, length: { maximum: 30}
	validates :year, presence: true, length: { is: 1 }
	validates :course, presence: true, length: { maximum: 15 }
	validates :contact_number, presence: true, length: { is: 11 }
	validates :email_address, presence: true, length: { maximum: 40 }
	validates :varsity_track, presence: true, length: { maximum: 15 }, inclusion: { in: TRACK }
	validates :debater_position, presence: true, length: { maximum: 23 }, inclusion: { in: POSITION }
	validates :total_debt, length: { maximum: 7 }, numericality: true
	validates :total_acquired_quota_points, length: { maximum: 3 }, numericality: true

	has_many :debt_settlements
	has_many :competition_debts
	has_many :acquired_quota_points, through: :activity_members
	has_many :activity_members
	has_many :tryout_intents
	has_many :competitons, through: :competition_debts

	validate :cannot_be_wrong

	def cannot_be_wrong
	 	if self.contact_number.length != 11
	      errors.add(:contact_number, "Must contain valid cellphone number! (11 digits)")
	    end

	    if self.vm_id > 999999
	      errors.add(:vm_id, "Must contain valid ID Number (6 digits)")
	    end
	end


	def to_s
		self.first_name + " " + self.last_name
	end

	# def calculate_total_debt
	# 	competition = Competition.find(self.competition_id)
	# 	vm = VarsityMember.find(self.varsity_member_id)

	# 	position = vm.debater_positon

		

	# 	competiton.avm.total_acquired_quota_points 
	# 	money = competition.quota_point_monetary_value


	# 	selfVarsityMember.all.each do |member|
	# 		member.total_debt = member.total_debt + (member.total_acquired_quota_points * member.competitons
	# 	end
	# end

	
end

app/controllers/varsity_members_controller.rb
class VarsityMembersController < ApplicationController
   load_and_authorize_resource
  def index
    @varsity_members = VarsityMember.all 

    render(:template => "varsity_members/index")
  end

  def show
    @varsity_member = VarsityMember.find(params[:id])
  end

  def new
    @varsity_member = VarsityMember.new

    render(:template => "varsity_members/new")
  end

  def create
    @varsity_member = VarsityMember.new(varsity_member_params)

    if @varsity_member.save
      redirect_to varsity_member_path(@varsity_member.id)
    else
      render(:template => "varsity_members/index")
    end
  end

  def edit
    @varsity_member = VarsityMember.find(params[:id])

    render(:templace => "varsity_members/edit")
  end

  def update
    @varsity_member = VarsityMember.find(params[:id])

    if @varsity_member.update(varsity_member_params)
      redirect_to varsity_member_path(@varsity_member)
    else
      render(:template => "varsity_members/edit")
    end
  end

  def destroy
    @varsity_member = VarsityMember.find(params[:id])
    @varsity_member.destroy!
    redirect_to varsity_members_path
  end

  def varsity_member_params
    params.require(:varsity_member).permit!
  end
end

app/helpers/varsity_members_helper.rb
module VarsityMembersHelper
end

app/views/varsity_members/_form.html.erb
<%= simple_form_for(@varsity_member) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :vm_id, :label => "ID" %>
  </div>

  <div class="form-inputs">
    <%= f.input :first_name %>
  </div>

  <div class="form-inputs">
    <%= f.input :last_name %>
  </div>

  <div class="form-inputs">
    <%= f.input :year, :collection => 1..5, :as => :select %>
  </div>

  <div class="form-inputs">
    <%= f.input :course %>
  </div>

  <div class="form-inputs">
    <%= f.input :contact_number %>
  </div>

  <div class="form-inputs">
    <%= f.input :email_address %>
  </div>

  <div class="form-inputs">
    <%= f.input :varsity_track, :as => :select, :collection => VarsityMember::TRACK, :include_blank => false %>
  </div>

  <div class="form-inputs">
    <%= f.input :debater_position, :as => :select, :collection => VarsityMember::POSITION, :include_blank => false %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/varsity_members/create.html.erb
<h1>VarsityMembers#create</h1>
<p>Find me in app/views/varsity_members/create.html.erb</p>

app/views/varsity_members/destroy.html.erb
<h1>VarsityMembers#destroy</h1>
<p>Find me in app/views/varsity_members/destroy.html.erb</p>

app/views/varsity_members/edit.html.erb
<h1>Editing Varsity Member</h1>

<%= render 'form' %>

<%= link_to 'Show', @varsity_member %> |
<%= link_to 'Back', varsity_members_path %>

app/views/varsity_members/index.html.erb
<h1>Listing Varsity Members</h1>

<table>
  <thead>
    <tr>
      <th>ID</th>
      <th>First Name</th>
      <th>Last Name</th>
      <th>Year</th>
      <th>Course</th>
      <th>Contact Number</th>
      <th>E-mail Address</th>
      <th>Varsity Track</th>
      <th>Debater Position</th>
      <th>Total Debt</th>
      <th>Total Acquired Quota Points</th>
      <th colspan="11"></th>
    </tr>
  </thead>

  <tbody>
    <% @varsity_members.each do |varsity_member| %>
      <tr>
        <td><%= varsity_member.vm_id %></td>
        <td><%= varsity_member.first_name %></td>
        <td><%= varsity_member.last_name %></td>
        <td><%= varsity_member.year %></td>
        <td><%= varsity_member.course %></td>
        <td><%= varsity_member.contact_number %></td>
        <td><%= varsity_member.email_address %></td>
        <td><%= varsity_member.varsity_track %></td>
        <td><%= varsity_member.debater_position %></td>
        <td><%= varsity_member.total_debt %></td>
        <td><%= varsity_member.total_acquired_quota_points %></td>
        <td><%= link_to 'Show', varsity_member %></td>
        <td><%= link_to 'Edit', edit_varsity_member_path(varsity_member) %></td>
        <td><%= link_to 'Destroy', varsity_member, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Varsity Member', new_varsity_member_path %>

<% @competition = Competition.find_by(presidential_approval_status: "Ongoing") %>

<% if @competition != nil %>
<%= button_to "End Training Session", edit_competition_path(@competition.id), method: :get %>
<% end %>

app/views/varsity_members/new.html.erb
<h1>New Varsity Member</h1>

<%= render 'form' %>

<%= link_to 'Back', varsity_members_path %>

app/views/varsity_members/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>ID:</strong>
  <%= @varsity_member.vm_id %>
</p>

<p>
  <strong>Name:</strong>
  <%= @varsity_member.first_name %> <%= @varsity_member.last_name %>
</p>

<p>
  <strong>Year:</strong>
  <%= @varsity_member.year %>
</p>

<p>
  <strong>Course:</strong>
  <%= @varsity_member.course %>
</p>

<p>
  <strong>Contact Number:</strong>
  <%= @varsity_member.contact_number %>
</p>

<p>
  <strong>Email Address:</strong>
  <%= @varsity_member.email_address %>
</p>

<p>
  <strong>Varsity Track:</strong>
  <%= @varsity_member.varsity_track %>
</p>

<p>
  <strong>Debater Position:</strong>
  <%= @varsity_member.debater_position %>
</p>

<%= link_to 'Edit', edit_varsity_member_path(@varsity_member) %> |
<%= link_to 'Back', varsity_members_path %>

app/views/varsity_members/update.html.erb
<h1>VarsityMembers#update</h1>
<p>Find me in app/views/varsity_members/update.html.erb</p>