config/routes.rb
Rails.application.routes.draw do

  resources :pages

  root 'pages#index'
  resources :varsity_members
  resources :tryout_intents
  resources :training_activities
  resources :debt_settlements
  resources :competitions
  resources :contingents
  resources :acquired_quota_points

  devise_for :officer_in_charges

devise_scope :officer_in_charges do
    get "signup", to: "devise/registrations#new"
    get "/signin" => "devise/sessions#new"
    post "/signin" => "devise/sessions#create"
    delete "/logout" => "devise/sessions#destroy"
end

end

app/models/competition.rb
class Competition < ActiveRecord::Base
	has_many :competition_debts
	has_many :contingents
	has_many :activity_members


	STATUS = ["Ongoing", "Completed", "Upcoming", "Processing"]

	validates :name, presence: true, length: { maximum: 30}
	validates :number_of_contingent, length: { maximum: 3 }, numericality: true
	validates :arqp_contingent_debater, length: { maximum: 3 }, numericality: true
	validates :arqp_contingent_adjudicator, length: { maximum: 3 }, numericality: true
	validates :arqp_non_contingent, length: { maximum: 3 }, numericality: true
	validates :presidential_approval_status, presence: true, inclusion: { in: STATUS }
	validates :end_date, presence: true
	validates :start_date, presence: true
	validates :quota_point_monetary_value, length: { maximum: 3 }, numericality: true

	validate :cannot_be_negative

	def cannot_be_negative
	 	if self.number_of_contingent <= 0
	      errors.add(:number_of_contingent, "Quantity must not be negative!")
	    end

	    if self.arqp_contingent_debater <= 0
	      errors.add(:number_of_contingent, "Quantity must not be negative!")
	    end

	    if self.arqp_contingent_adjudicator <= 0
	      errors.add(:number_of_contingent, "Quantity must not be negative!")
	    end

	    if self.arqp_non_contingent <= 0
	      errors.add(:number_of_contingent, "Quantity must not be negative!")
	    end

	    if self.quota_point_monetary_value <= 0
	      errors.add(:number_of_contingent, "Quantity must not be negative!")
	    end
	end

  validate :status_check
  def status_check
      competition = Competition.find_by(presidential_approval_status: "Ongoing")

      if self.presidential_approval_status == "Ongoing" && competition != nil
        raise "Error: A competition is currently ongoing"
        errors.add(:presidential_approval_status, "A competition is currently ongoing")
      end

      if self.presidential_approval_status == "Completed" 
        raise "Error: Competition is alredy completed"
        errors.add(:presidential_approval_status, "Competition is alredy completed")
      end
  end
	  def ongoing!
    if self.presidential_approval_status == "Ongoing"
      raise "ERROR: Competition already Ongoing" 
    else
      self.update!(presidential_approval_status: "Ongoing")
    end 
  end

  def completed!
    if self.presidential_approval_status == "Completed"
      raise "ERROR: Competition already Completed" 
    else
      self.update!(presidential_approval_status: "Completed")
    end 
  end

  def upcoming!
      if self.presidential_approval_status == "Upcoming"
        raise "ERROR: Competition already Upcoming" 
      else
        self.update!(presidential_approval_status: "Upcoming")
      end
  end

  def processing!
    result = false
      if self.presidential_approval_status == "Processing" || self.presidential_approval_status == "Completed"
        raise "ERROR: Competition already Processing" 
        return result = false
      else
        self.update!(presidential_approval_status: "Processing")
        return result = true
      end
  end

  after_update :total_debt, if:  Proc.new { |competition| competition.presidential_approval_status == "Processing" } #{competition.presidential_approval_status == "processing"}
  
  def total_debt 
    temp = 0
    debt = 0

      VarsityMember.all.each do |vmember|
      #vmember.activity_members.each do |amember|
         
         #competition = Competition.find(amember.competition_id)
         competition = Competition.find_by(presidential_approval_status: "Processing")
         #vm = VarsityMember.find(amember.varsity_member_id)
         if vmember.debater_position == "Contingent Debater"

          temp = competition.arqp_contingent_debater - vmember.total_acquired_quota_points
            if temp > 0 
                debt = temp * competition.quota_point_monetary_value
                debt_total = vmember.total_debt + debt
                vmember.update(:total_debt => debt_total)
            end
        
        elsif vmember.debater_position == "Contingent Adjudicator"

              temp = competition.arqp_contingent_adjudicator - vmember.total_acquired_quota_points
            if temp > 0 
                debt = temp * competition.quota_point_monetary_value
                debt_total = vmember.total_debt + debt
                vmember.update(:total_debt => debt_total)
            end

        elsif vmember.debater_position == "Non-contingent"

              temp = competition.arqp_non_contingent - vm.total_acquired_quota_points
            if temp > 0 
                debt = temp * competition.quota_point_monetary_value
                debt_total = vmember.total_debt + debt
                vmember.update(:total_debt => debt_total)
            end
        end
    end

    self.update!(presidential_approval_status: "Completed")
  end

end

app/controllers/competitions_controller.rb
class CompetitionsController < ApplicationController
   load_and_authorize_resource
  def index
    @competitions = Competition.all 

    render(:template => "competitions/index")
  end

  def show
    @competition = Competition.find(params[:id])
  end

  def new
    @competition = Competition.new

    render(:template => "competitions/new")
  end

  def create
    @competition = Competition.new(competition_params)

    if @competition.save
      redirect_to competition_path(@competition.id)
    else
      render(:template => "competitions/index")
    end
  end

  def edit
    @competition = Competition.find(params[:id])

    render(:templace => "competitions/edit")
  end

  def update
    @competition = Competition.find(params[:id])

    if @competition.update(competition_params)
      redirect_to competition_path(@competition)
    else
      render(:template => "competitions/edit")
    end
  end

  def destroy
    @competition = Competition.find(params[:id])
    @competition.destroy!
    redirect_to competitions_path
  end

  def competition_params
    params.require(:competition).permit!
  end
end

app/helpers/competitions_helper.rb
module CompetitionsHelper
end

app/views/competitions/_form.html.erb
<%= simple_form_for(@competition) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name %>
  </div>

  <div class="form-inputs">
    <%= f.input :number_of_contingent %>
  </div>

  <div class="form-inputs">
    <%= f.input :arqp_contingent_debater, :label => "Assigned Required Quota Points for Contingent Debater" %>
  </div>

  <div class="form-inputs">
    <%= f.input :arqp_contingent_adjudicator, :label => "Assigned Required Quota Points for Contingent Adjudicator" %>
  </div>

  <div class="form-inputs">
    <%= f.input :arqp_non_contingent, :label => "Assigned Required Quota Points for Non-Contingent" %>
  </div>

  <div class="form-inputs">
    <%= f.input :presidential_approval_status, :as => :select, :collection => Competition::STATUS, :label => "Presidential Approval Status" %>
  </div>

  <div class="form-inputs">
    <%= f.label :start_date, "Start Date" %>
    <%= f.date_select :start_date %>
  </div>

  <div class="form-inputs">
    <%= f.label :start_date, "End Date" %>
    <%= f.date_select :end_date %>
  </div>

  <div class="form-inputs">
    <%= f.input :quota_point_monetary_value %>
  </div>

  <div class="form-actions">
    <%= f.button :submit, data: { confirm: 'Are you sure?'}%>
  </div>
<% end %>

app/views/competitions/create.html.erb
<h1>Competitions#create</h1>
<p>Find me in app/views/competitions/create.html.erb</p>

app/views/competitions/destroy.html.erb
<h1>Competitions#destroy</h1>
<p>Find me in app/views/competitions/destroy.html.erb</p>

app/views/competitions/edit.html.erb
<h1>Editing Competition</h1>

<%= render 'form' %>

<%= link_to 'Show', @competition %> |
<%= link_to 'Back', competitions_path %>

app/views/competitions/index.html.erb
<h1>Listing Competitions</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Number of Contingent</th>
      <th>Contingent Debater</th>
      <th>Contingent Adjudicator</th>
      <th>Non-Contingent</th>
      <th>Presidential Approval Status</th>
      <th>Start Date</th>
      <th>End Date</th>
      <th>Quota Point Monetary Value</th>
      <th colspan="9"></th>
    </tr>
  </thead>

  <tbody>
    <% @competitions.each do |competition| %>
      <tr>
        <td><%= competition.name %></td>
        <td><%= competition.number_of_contingent %></td>
        <td><%= competition.arqp_contingent_debater %></td>
        <td><%= competition.arqp_contingent_adjudicator %></td>
        <td><%= competition.arqp_non_contingent %></td>
        <td><%= competition.presidential_approval_status %></td>
        <td><%= competition.start_date %></td>
        <td><%= competition.end_date %></td>
        <td><%= competition.quota_point_monetary_value %></td>
        <td><%= link_to 'Show', competition %></td>
        <td><%= link_to 'Edit', edit_competition_path(competition) %></td>
        <td><%= link_to 'Destroy', competition, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Competition', new_competition_path %>
<%= link_to 'Home', pages_path %>

app/views/competitions/new.html.erb
<h1>New Competition</h1>

<%= render 'form' %>

<%= link_to 'Back', competitions_path %>

app/views/competitions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @competition.name %>
</p>

<p>
  <strong>Number of Contingent:</strong>
  <%= @competition.number_of_contingent %>
</p>

<p>
  <strong>Contingent Debater:</strong>
  <%= @competition.arqp_contingent_debater %>
</p>

<p>
  <strong>Contingent Adjudicator:</strong>
  <%= @competition.arqp_contingent_adjudicator %>
</p>

<p>
  <strong>Non-Contingent:</strong>
  <%= @competition.arqp_non_contingent %>
</p>

<p>
  <strong>Presidential Approval Status:</strong>
  <%= @competition.presidential_approval_status %>
</p>

<p>
  <strong>Start Date:</strong>
  <%= @competition.start_date %>
</p>

<p>
  <strong>End Date:</strong>
  <%= @competition.end_date %>
</p>

<%= link_to 'Edit', edit_competition_path(@competition) %> |
<%= link_to 'Back', competitions_path %>

app/views/competitions/update.html.erb
<h1>Competitions#update</h1>
<p>Find me in app/views/competitions/update.html.erb</p>